# Generated by Django 2.1.4 on 2019-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20190102_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Page Name'),
            preserve_default=False,
        ),
    ]
